name: terraform validation

on:
  push:
    branches:
      - master
      - feature/**
      - chore/github-action
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
      - name: fmt
        run: terraform fmt -check
